version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rs_postgres
    environment:
      POSTGRES_DB: retail_sync
      POSTGRES_USER: rs_admin
      POSTGRES_PASSWORD: rs_dev_2026
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: rs_redis
    ports:
      - '6379:6379'

volumes:
  pgdata:
